"""id has no autoincrement

Revision ID: 5d2a2405ddb8
Revises: de1e9881bf8d
Create Date: 2023-05-18 00:09:08.560976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d2a2405ddb8'
down_revision = 'de1e9881bf8d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_id', 'questions', ['id'])
    op.execute('DROP SEQUENCE questions_id_seq CASCADE')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_id', 'questions', type_='unique')
    op.execute('CREATE SEQUENCE questions_id_seq')
    op.execute(
        """
        ALTER TABLE questions ALTER COLUMN id 
        SET DEFAULT nextval('questions_id_seq');
        """
    )
    # ### end Alembic commands ###
