"""change table audio

Revision ID: 6a355b482504
Revises: 9e0c9aad6dce
Create Date: 2023-05-19 18:58:21.767169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a355b482504'
down_revision = '9e0c9aad6dce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('audios_uuid_key', 'audios', type_='unique')
    op.create_unique_constraint('unique_id', 'audios', ['id'])
    op.drop_column('audios', 'uuid')
    op.execute(
        '''
        CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
        ALTER TABLE audios ALTER COLUMN id DROP DEFAULT;
        ALTER TABLE audios ALTER COLUMN id TYPE UUID USING (uuid_generate_v4());
        '''
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audios', sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint('unique_id', 'audios', type_='unique')
    op.create_unique_constraint('audios_uuid_key', 'audios', ['uuid'])
    op.execute(
        '''
        ALTER TABLE audios ALTER COLUMN id DROP DEFAULT;
        ALTER TABLE audios ALTER COLUMN id TYPE int USING nextval('audios_id_seq')
        '''
    )
    # ### end Alembic commands ###
